AppBootStrapped:
   message:
     en : 'Application BootStrapped'
     se : 'Ansökan bootstrapped'
TestingStarted:
    message:
      en: 'Started...'
      se: 'Satte igång...'
PingingHosts:
    message:
      en: 'Pinging Host'
      se: 'Pinging värd'
NoFileExists:
   message:
     en : 'No Such File Exists'
     se : 'Ingen sadan fil existerar'
GreenletJoinError:
   message:
     en: 'Not able to join greenlets'
     se: 'Det går inte att ansluta greenlets'
GreenLetCompletion:
    message:
      en: 'Testing Completed'
      se: 'provning som genomförts'
RenderHTML:
    message:
      en: 'Rendering HTML'
      se: 'Rendering HTML'
FileDownload:
    message:
      en: 'Report file can be accessed '
      se: 'Rapportera fil kan nås '